# azure-pipelines.yml
trigger:
  - main  # Trigger the pipeline on changes to the main branch

pool:
  vmImage: 'ubuntu-latest'  # Use the latest Ubuntu image

steps:
  - script: echo "Starting the build process..."
    displayName: 'Initial Step'

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'  # Specify the Python version
      addToPath: true

  - script: |
      pip install -r requirements.txt  # Install dependencies
    displayName: 'Install Dependencies'

  - script: |
      python iris_1.py  # Run your training script
    displayName: 'Train Model'

  - task: PublishPipelineArtifact@1
    inputs:
      artifactName: 'model'
      targetPath: 'decision_tree_model.pkl'  # Path to the model file

  - script: |
      echo "Model training completed and saved."
    displayName: 'Completion Message'
