# azure-pipelines.yml
trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    echo "Installing dependencies..."
    pip install -r requirements.txt
  displayName: 'Install Dependencies'

- script: |
    echo "Running tests..."
    pytest
  displayName: 'Run Tests'

- script: |
    echo "Building the application..."
    python build.py
  displayName: 'Build Application'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Artifact'
